# Generated by Django 4.2.5 on 2023-09-20 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='walletmodel',
            old_name='user',
            new_name='username',
        ),
    ]
