# Generated by Django 4.2.5 on 2023-09-21 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_rename_user_walletmodel_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='walletmodel',
            old_name='username',
            new_name='user',
        ),
    ]
